name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/stats.svg
          base: repositories
          base_indepth: yes
          plugin_stars: yes
          plugin_stars_limit: 0
          config_display: large
          config_animations: no

  top-langs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/top-langs.svg
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          config_display: large
          config_animations: no
